import { PrismaClient, PrefectureEnum } from '@prisma/client'

const prisma = new PrismaClient()

export const createPrefectures = async () => {
  await prisma.prefecture.createMany({
    data: [
      { id: PrefectureEnum.HOKKAIDO, name: '北海道', nameKana: 'ほっかいどう' },
      { id: PrefectureEnum.AOMORI, name: '青森県', nameKana: 'あおもりけん' },
      { id: PrefectureEnum.IWATE, name: '岩手県', nameKana: 'いわてけん' },
      { id: PrefectureEnum.MIYAGI, name: '宮城県', nameKana: 'みやぎけん' },
      { id: PrefectureEnum.AKITA, name: '秋田県', nameKana: 'あきたけん' },
      { id: PrefectureEnum.YAMAGATA, name: '山形県', nameKana: 'やまがたけん' },
      { id: PrefectureEnum.FUKUSHIMA, name: '福島県', nameKana: 'ふくしまけん' },
      { id: PrefectureEnum.IBARAKI, name: '茨城県', nameKana: 'いばらきけん' },
      { id: PrefectureEnum.TOCHIGI, name: '栃木県', nameKana: 'とちぎけん' },
      { id: PrefectureEnum.GUNMA, name: '群馬県', nameKana: 'くんまけん' },
      { id: PrefectureEnum.SAITAMA, name: '埼玉県', nameKana: 'さいたまけん' },
      { id: PrefectureEnum.CHIBA, name: '千葉県', nameKana: 'ちばけん' },
      { id: PrefectureEnum.TOKYO, name: '東京都', nameKana: 'とうきょうと' },
      { id: PrefectureEnum.KANAGAWA, name: '神奈川県', nameKana: 'かながわけん' },
      { id: PrefectureEnum.NIIGATA, name: '新潟県', nameKana: 'にいがたけん' },
      { id: PrefectureEnum.TOYAMA, name: '富山県', nameKana: 'とやまけん' },
      { id: PrefectureEnum.ISHIKAWA, name: '石川県', nameKana: 'いしかわけん' },
      { id: PrefectureEnum.FUKUI, name: '福井県', nameKana: 'ふくいけん' },
      { id: PrefectureEnum.YAMANASHI, name: '山梨県', nameKana: 'やまなしけん' },
      { id: PrefectureEnum.NAGANO, name: '長野県', nameKana: 'ながのけん' },
      { id: PrefectureEnum.GIFU, name: '岐阜県', nameKana: 'ぎふけん' },
      { id: PrefectureEnum.SHIZUOKA, name: '静岡県', nameKana: 'しずおかけん' },
      { id: PrefectureEnum.AICHI, name: '愛知県', nameKana: 'あいちけん' },
      { id: PrefectureEnum.MIE, name: '三重県', nameKana: 'みえけん' },
      { id: PrefectureEnum.SHIGA, name: '滋賀県', nameKana: 'しがけん' },
      { id: PrefectureEnum.KYOTO, name: '京都府', nameKana: 'きょうとふ' },
      { id: PrefectureEnum.OSAKA, name: '大阪府', nameKana: 'おおさかふ' },
      { id: PrefectureEnum.HYOGO, name: '兵庫県', nameKana: 'ひきょうけん' },
      { id: PrefectureEnum.NARA, name: '奈良県', nameKana: 'ならけん' },
      { id: PrefectureEnum.WAKAYAMA, name: '和歌山県', nameKana: 'わかやまけん' },
      { id: PrefectureEnum.TOTTORI, name: '鳥取県', nameKana: 'とっとりけん' },
      { id: PrefectureEnum.SHIMANE, name: '島根県', nameKana: 'しまねけん' },
      { id: PrefectureEnum.OKAYAMA, name: '岡山県', nameKana: 'おかやまけん' },
      { id: PrefectureEnum.HIROSHIMA, name: '広島県', nameKana: 'ひろしまけん' },
      { id: PrefectureEnum.YAMAGUCHI, name: '山口県', nameKana: 'やまぐちけん' },
      { id: PrefectureEnum.TOKUSHIMA, name: '徳島県', nameKana: 'とくしまけん' },
      { id: PrefectureEnum.KAGAWA, name: '香川県', nameKana: 'かがわけん' },
      { id: PrefectureEnum.EHIME, name: '愛媛県', nameKana: 'えひめけん' },
      { id: PrefectureEnum.KOCHI, name: '高知県', nameKana: 'こうちけん' },
      { id: PrefectureEnum.FUKUOKA, name: '福岡県', nameKana: 'ふくおかけん' },
      { id: PrefectureEnum.SAGA, name: '佐賀県', nameKana: 'さがけん' },
      { id: PrefectureEnum.NAGASAKI, name: '長崎県', nameKana: 'ながさきけん' },
      { id: PrefectureEnum.KUMAMOTO, name: '熊本県', nameKana: 'くまもとけん' },
      { id: PrefectureEnum.OITA, name: '大分県', nameKana: 'おおいたけん' },
      { id: PrefectureEnum.MIYAZAKI, name: '宮崎県', nameKana: 'みやざきけん' },
      { id: PrefectureEnum.KAGOSHIMA, name: '鹿児島県', nameKana: 'かごしまけん' },
      { id: PrefectureEnum.OKINAWA, name: '沖縄県', nameKana: 'おきなわけん' },
    ],
  })
}
